### ISSUE TITLE
Light Code Refactoring

### ISSUE THREAD

**Issue by pechouc** [pyronear/pyro-platform#12]
# Starting point of the issue

> This comment is more of a question I am asking myself than a change request. Would it be cleaner to directly call the functions instead of their output when building the `body` object? 
> 
> This might not be clear said this way but so far, we generally create a new variable (here `map_layers_button`) which simply contains the output of the related function (`build_layer_style_button`) and then, we call it without any particular transformation in the app layout block (at line 123 in this case). Equivalently, we could directly call the function at line 123 and skip the creation of the object. 
>
> I don't know what the best practice is here and I don't have any strong opinion, but I guess that we would spare quite a few lines and variables by doing so, which can only make our code more readable, right?

_Originally posted by @pechouc in https://github.com/pyronear/pyronear-webapp/pull/10#discussion_r515630455_

# Scope of the issue 

Following the quick discussion mentioned above, the aim of this issue is to weigh the pros and the cons of a light refactoring of the code that we have written so far. The main goal of the edits would be to eliminate the instantiations we are currently making and could avoid in files like ```alerts.py```, ```risks.py``` and ```homepage.py```.

# Why do such edits? 

The fact that we systematically instantiate each object in the code creates multiple variables that could be avoided by directly calling the functions instead. 

Avoiding these instantiations would allow us to:

* Clarify the code since for each component of the web-application, we have at the moment: a function name, a variable name and an ```id``` used in the callbacks. Sometimes, they are the same and in other cases, they differ which can bring confusions in both situations.

* Keep standalone functions. To give an example of this issue, one can look at the ```AlertsApp()``` for instance: the function uses several variables that have been defined outside of it (```nav```, ```space```, ```layer_style_button```...). 

* Spare a few lines of code. 

# Other remarks

* It seems that this practice of systematically instantiating the objects derives from the [code](https://github.com/joelsewhere/dash_app) that was provided with the tutorial that we followed initially to build the structure of the app. 

* Example of a chunk of code that would be edited:

```
# ------------------------------------------------------------------------------
# App layout (finally!)

# Instantiating the navigation bar
nav = Navbar()

# Adding a first separator between the navigation bar and the button
space = dcc.Markdown('---')

# Instantiating the button to change the map layer style
layer_style_button = build_layer_style_button()

# Adding a second separator between the button and the map
separator = dcc.Markdown('---')

# Finally instantiating the map object
map_object = build_alerts_map()


# Gathering all these elements in a HTML Div and having it returned by the AlertsApp function
def AlertsApp():
    layout = [nav,
              space,
              layer_style_button,
              separator,
              map_object]

    return html.Div(layout)
```

* It could give, after the refactoring:

```
# ------------------------------------------------------------------------------
# App layout (finally!)

def AlertsApp():
    layout = [Navbar(),   # Instantiating the navigation bar
              dcc.Markdown('---'),   # Adding a first separator between the navigation bar and the button
              build_layer_style_button(),   # Instantiating the button to change the map layer style
              dcc.Markdown('---'),   # Adding a second separator between the button and the map
              build_alerts_map()]   # Finally instantiating the map object

    return html.Div(layout)
```

# Question

Let me know what you think of this proposed modification! Do we all agree on this change? Do you fear it might make the code less explicit?

**Comment by nrslt** [comment]
I am kind of new to these 'best practices' but I see how it could benefit our code in terms of size/clarity/avoiding errors with ids callbacks.
I can definitely help on this one, let me know wether you want to split the work or if only one person takes care of it for consistency purposes.

**Comment by pechouc** [comment]
> I can definitely help on this one, let me know wether you want to split the work or if only one person takes care of it for consistency purposes.

Cool, thanks a lot! If that suits you, I will open the PR with the edits mentioned in the issue (I doubt it will be long enough for two people to be occupied by this) and we can continue the discussion there, so that you can review the modifications or propose others that we might have missed 😊

**Comment by VincGargasson** [comment]
Good idea ! As @nrslt  I don't know much about this type of best practice but I guess, if the code is more readable and concise, this must be a good practice. 💯
