### ISSUE TITLE
ci: Issue with rmi unused and dangling images 

### ISSUE THREAD

**Issue by Akilditu** [pyronear/pyro-platform#128]
Hi @frgfm there is an error caused deploy-dev job on release as you can see [here](https://github.com/pyronear/pyro-platform/actions/runs/6783271093/job/18437235963) 

Trying to delete the current image running and then causing -->` err: Error response from daemon: conflict: unable to delete a8d09517dc80 (cannot be forced) - image is being used by running container 7bd1a0897dd8`

Shouldn't we use something like `docker image prune -a` ?

**Comment by MateoLostanlen** [comment]
maybe just remove the "-f" : https://github.com/pyronear/pyro-platform/pull/123#pullrequestreview-1712869038
