### ISSUE TITLE
Zoom on alert image

### ISSUE THREAD

**Issue by fe51** [pyronear/pyro-platform#144]
It is not currently possible to zoom in on the image of an alert.

As a user, I'd like to be able to zoom in on the image of an alert in order to better visualise the fire outbreak/smoke

**Comment by wrousseau** [comment]
I'm taking this issue (Woody), can you assign me to it?

**Comment by RonanMorgan** [comment]
@wrousseau still motivated ? :)

**Comment by vanderlindenma** [comment]
https://github.com/pyronear/pyro-platform/pull/169
