### ISSUE TITLE
Updating HTML page title & logo

### ISSUE THREAD

**Issue by frgfm** [pyronear/pyro-platform#17]
Hey there :wave: 

I just opened the app and noticed that the page title and logo are still the default Dash : 
![webapp_title](https://user-images.githubusercontent.com/26927750/98828117-f78dd200-2437-11eb-9a58-f7bcbb05465c.png)

Not sure how, but it would be great to update those :) 
cc @VincGargasson @pechouc @nrslt @abdi-adel @Akilditu

**Comment by nrslt** [comment]
I'm on it!
