### ISSUE TITLE
[Planning] Next Steps for the Platform

### ISSUE THREAD

**Issue by pechouc** [pyronear/pyro-platform#36]
# Goal of the issue

* The goal of this issue is to discuss the priorities for the platform and define a roadmap for our work in the coming months. 

* More concretely, it aims at: 
  * gathering a list of modifications (improvements, redesigning, new features...) we want to bring to the platform;
  * defining priority and difficulty levels (based on a rough grade system) for each of them.

* We will then be able to choose on what topics each of us wants to work (and with what timeline) more easily.

# Initial proposal

* I have prepared a first draft of the roadmap in [this Google Doc](https://docs.google.com/document/d/17veJWmzZ9rhvFFuh_CMD9mPxrn1E8WlXoEStIADIFl8/edit?usp=sharing). 

* The current summary looks like this:

![Capture d’écran 2020-12-26 à 14 41 45](https://user-images.githubusercontent.com/63041127/103152470-996b4300-4788-11eb-8e78-85d7dcd23ce7.png)

* It is incomplete for three main reasons:
  * the overall format of the roadmap (eg. the three categories of modifications) might not be the most appropriate;
  * tasks or even categories of tasks have surely been omitted in this first draft;
  * the priority and difficulty levels should be discussed, in order to improve the way tasks are ranked.

# Question

* I would be glad to get your inputs on these three main questions:
  * does the overall format of the roadmap and document seem clear and actionable to you? how would you improve it? 
  * do you see tasks and modifications that we want to bring to the platform missing in the document? 
  * what do you think about the priority and difficulty levels? how you would make them more accurate?

* Naturally, the goal of this issue is also to start a more general discussion about the next steps for the platform, so feel free to bring in any other related topic!

**Comment by pechouc** [comment]
# Additional ideas from 01/13 meeting

* Add a visual indication of the orientation and scope of the detection 
* Support to firefighters' intervention and site access
* Basic human activity indications: day of the week, holidays, industrial sites, identify large gatherings...

**Comment by Akilditu** [comment]
Thanks for the issue @pechouc ! 

Maybe the next step is to decide which tasks are the one we wanna prioritize and create one dedicated issue for each

**Comment by pechouc** [comment]
I am closing this issue since the discussions of the past few weeks have widely covered the topic. These are summarised in [this Notion page](https://www.notion.so/pyronear/Next-Steps-e31fb4baa89e441dbf855f270a1c82f9).
