### ISSUE TITLE
[API] Fetch alerts metadata from API

### ISSUE THREAD

**Issue by Akilditu** [pyronear/pyro-platform#38]
2 things are still pending regarding `alerts` API calls : 

- [ ] Make actual calls to instantiate `alerts` metadata on some [remaining attributes ](https://github.com/pyronear/pyro-platform/blob/4a11c57dd82900f8eb6b0bc956125505f5eeed1b/app/utils.py#L192)
- [ ] Propose a relevant alternative to the 10 seconds scheduler or deal with backend ressources so that it never crashes

I would rather go for the web-hook option but I'm not sure that Dash handles this natively. Maybe we could use Flask endpoints that accept POST requests but then again I'm not sure that we could use it to trigger callbacks. 

Would be great to have your inputs on the 2nd point @frgfm @chloeskt @jeanpasquier75 @florianriche 👋

**Comment by frgfm** [comment]
@florianriche mentioned webhook a few months back, but I think we need to identify the proper way to handle this.

First, the big choice: if we have 20 SDIS using the platform, should we deploy 1 server with multiple accesses, or 20 servers?

Now assuming we deploy only 1 server for the sake of efficiency: let's imagine we have 100 firefighters connected to the platform. We have two options here:
1. User independent: each user session is fetching its own data from the API according to the active creds/scope. Easier for data privacy, really bad for latency and server load.
2. Server-level: the platform server is receiving (via webhooks for instance) all the information from the API with appropriate scope, the user session will only receive the filtered information corresponding to its scope

This will largely impact future developments of the platform, so we need to decide first. My opinion is rather simple:
- I prefer having 1 server for the whole country (as long as latency is acceptable), and using server-level transfer. Mostly for consumption efficiency
- the minimum effort which preserves privacy without implementing much: 1 server per SDIS, and each user fetches its data. Easy, but not really responsible. Plus it will put additional constraints on the back-end team for scaling up the infra
What do you think?

**Comment by frgfm** [comment]
Also, regarding your second point @Akilditu, I think we started an insightful discussion in #21

**Comment by frgfm** [comment]
Not sure, but perhaps we can close #21 as both issues seem to be about the very same topic?

**Comment by frgfm** [comment]
@florianriche would you mind reporting back here what you had found (resources / reference) about webhooks with flask? :pray:

**Comment by frgfm** [comment]
Hello @pyronear/front-end :wave: 

So we have some news. Most likely, we're gonna add a callback on alert creation routes that will make an HTTP POST request to the platform. This POST request will contain the alert so you don't need to request it later on.

This means that you would need to implement something to process this POST request on your Flask server. Do you think it's doable? Happy to help with this!

**Comment by Akilditu** [comment]
> Hello @pyronear/front-end 👋
> 
> So we have some news. Most likely, we're gonna add a callback on alert creation routes that will make an HTTP POST request to the platform. 
 Great news ! 

> This POST request will contain the alert so you don't need to request it later on.
We would need to describe the exact metadata that you send within de request (e.g all fields related to the alert table)

> This means that you would need to implement something to process this POST request on your Flask server. Do you think it's doable? Happy to help with this!
I think it's definitely doable, defining a new route as an endpoint would most likely do the job. Something like : 
```
@server.route(’/alerts-results’,methods = [‘POST’])
def result():
if request.method == ‘POST’:
result = request.form
```
I'am actually far from being an expert on this so any wise input would be more than welcome. We also have to anticipate a refresh each time a post is processed on the platform side (then triggering our callbacks)

**Comment by Akilditu** [comment]
> Hello @pyronear/front-end 👋
> 
> So we have some news. Most likely, we're gonna add a callback on alert creation routes that will make an HTTP POST request to the platform. This POST request will contain the alert so you don't need to request it later on.
> 
> This means that you would need to implement something to process this POST request on your Flask server. Do you think it's doable? Happy to help with this!

**Comment by frgfm** [comment]
@Akilditu I was thinking about posting you the exact same thing that you were receiving: instead of fetching the list of alerts, you would get a payload with a single alert. 

For reference here is a sample payload of what you would get: 
```
{
"id": 0,
"created_at": "2019-08-24T14:15:22Z",
"media_id": 0,
"lat": 44.765181,
"lon": 4.51488,
"event_id": 0,
"type": "start",
"is_acknowledged": false,
"device_id": 0
}
```

Let us know if you thought about something different!

**Comment by Akilditu** [comment]
> @Akilditu I was thinking about posting you the exact same thing that you were receiving: instead of fetching the list of alerts, you would get a payload with a single alert.
> 
> For reference here is a sample payload of what you would get:
> 
> ```
> {
> "id": 0,
> "created_at": "2019-08-24T14:15:22Z",
> "media_id": 0,
> "lat": 44.765181,
> "lon": 4.51488,
> "event_id": 0,
> "type": "start",
> "is_acknowledged": false,
> "device_id": 0
> }
> ```
> 
> Let us know if you thought about something different!

Sounds great, had this in mind :)

**Comment by frgfm** [comment]
My bad, here is what you would actually get after the latest updates:
```
{
"id": 0,
"created_at": "2019-08-24T14:15:22Z",
"media_id": 0,
"lat": 44.765181,
"lon": 4.51488,
"event_id": 0,
"is_acknowledged": false,
"azimuth": 0,
"device_id": 0
}
```

**Comment by frgfm** [comment]
Alright, I think I managed to get things working on the API side!
Admins of the API only have to add the name of the route to add a callback to + the URL to post the information and it should be working :) 

So, we need to implement a POST method for "alert_notification" on this repo. Two questions:
- **Implementation of the POST method**: do you need help with this? If so, could you point to some documentation?
- **Integration of the notification**: I have no idea how you want to handle this event-based interaction, but this needs some thinking early on.

**Comment by Akilditu** [comment]
> Alright, I think I managed to get things working on the API side!
> Admins of the API only have to add the name of the route to add a callback to + the URL to post the information and it should be working :)
> 
> So, we need to implement a POST method for "alert_notification" on this repo. Two questions:
> 
> * **Implementation of the POST method**: do you need help with this? If so, could you point to some documentation?
> * **Integration of the notification**: I have no idea how you want to handle this event-based interaction, but this needs some thinking early on @pyronear/front-end

Good news ! 

I kinda spent few time on this : the idea here is to integrate our Dash app in a proper Flask one so that we can create a specific route that will be able to process API POST data. 

I actually succeeded in doing so but then the tricky part is to pass this payload to the Dash callbacks which seems to be a lot more difficult (almost 0 ressources on this). 

I'm available for a deep dive into this black sea ...
