### ISSUE TITLE
Images are not available anymore through API calls

### ISSUE THREAD

**Issue by Akilditu** [pyronear/pyro-platform#74]
It's been a month now that img urls are empty while fetching using `get_media_url()`

To me, issues could be - following the most likely : 

- On devices's side if their creds prevent images to be sent to API ? 
- On API's side, if route broken or so ? 
- On qarnot's side ?

What do you guys think @frgfm, @florianriche , @MateoLostanlen, @pechouc ?

**Comment by frgfm** [comment]
Sorry for the late reply!

I can run some tests, but have you checked that we can do it properly outside of the platform?
If that's the case, the problem comes from the platform, otherwise it's on the backend side!

**Comment by frgfm** [comment]
According to our tests yesterday @Akilditu, I think we can close this issue right?

**Comment by Akilditu** [comment]
@Akilditu still some issues regarding ongoing experiment but I guess it's more on hardware's side than API. 

So yes this can be closed.
